# Generated by Django 2.1 on 2018-08-26 05:33

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=150)),
                ('description', models.TextField(help_text='The descriptions and rules of the category.')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(help_text='The time elapsed in seconds for the record.')),
                ('date', models.DateField(default=datetime.date.today, help_text='The date the record was made.')),
                ('video_url', models.URLField(help_text='A link to a recording of the record.')),
                ('category', models.ForeignKey(help_text='The category for this record', on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Category')),
                ('user', models.ForeignKey(help_text='The user making the record.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(help_text='The name of the course.', max_length=150)),
                ('course_number', models.PositiveIntegerField(help_text='The course number.', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SevenStarCourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(help_text='The time elapsed in seconds for the record.')),
                ('date', models.DateField(default=datetime.date.today, help_text='The date the record was made.')),
                ('video_url', models.URLField(help_text='A link to a recording of the record.')),
                ('course', models.ForeignKey(help_text='The course for this record', on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Course')),
                ('user', models.ForeignKey(help_text='The user making the record.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SixStarCourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(help_text='The time elapsed in seconds for the record.')),
                ('date', models.DateField(default=datetime.date.today, help_text='The date the record was made.')),
                ('video_url', models.URLField(help_text='A link to a recording of the record.')),
                ('course', models.ForeignKey(help_text='The course for this record', on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Course')),
                ('user', models.ForeignKey(help_text='The user making the record.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
