# Generated by Django 2.1 on 2018-08-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_auto_20180826_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='categoryrecord',
            name='category',
            field=models.ForeignKey(help_text='The category for this record.', on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Category'),
        ),
        migrations.AlterField(
            model_name='sevenstarcourserecord',
            name='course',
            field=models.ForeignKey(help_text='The course for this record.', on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Course'),
        ),
        migrations.AlterField(
            model_name='sixstarcourserecord',
            name='course',
            field=models.ForeignKey(help_text='The course for this record.', on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Course'),
        ),
    ]
