# Generated by Django 2.1 on 2018-08-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_auto_20180826_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_number']},
        ),
        migrations.AlterModelOptions(
            name='sevenstarcourserecord',
            options={'ordering': ['course__course_number', 'time']},
        ),
        migrations.AlterModelOptions(
            name='sixstarcourserecord',
            options={'ordering': ['course__course_number', 'time']},
        ),
    ]
