# Generated by Django 2.1 on 2018-08-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0005_auto_20180826_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryrecord',
            options={'ordering': ['category__id', 'time']},
        ),
    ]
