# Generated by Django 2.1 on 2018-08-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0007_auto_20180827_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(default='https://via.placeholder.com/320x224', help_text='Preview image for the course.', upload_to=''),
        ),
    ]
