# Generated by Django 2.1 on 2018-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_course_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(default='https://via.placeholder.com/320x224', help_text='Preview image for the course.', upload_to='courses/'),
        ),
    ]
