# Generated by Django 2.1 on 2018-09-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0010_add_course_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryrecord',
            options={'ordering': ['category__id', 'time', 'date']},
        ),
        migrations.AlterModelOptions(
            name='sevenstarcourserecord',
            options={'ordering': ['course__course_number', 'time', 'date']},
        ),
        migrations.AlterModelOptions(
            name='sixstarcourserecord',
            options={'ordering': ['course__course_number', 'time', 'date']},
        ),
    ]
