# Generated by Django 2.1 on 2018-09-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0011_auto_20180901_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview_image',
            field=models.ImageField(default='https://via.placeholder.com/320x224', help_text='Preview image for the category.', upload_to='categories/'),
        ),
    ]
