# Generated by Django 2.1 on 2018-09-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0013_create_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrecord',
            name='video_url',
            field=models.URLField(help_text='A link to a recording of the record.', verbose_name='video URL'),
        ),
        migrations.AlterField(
            model_name='sevenstarcourserecord',
            name='video_url',
            field=models.URLField(help_text='A link to a recording of the record.', verbose_name='video URL'),
        ),
        migrations.AlterField(
            model_name='sixstarcourserecord',
            name='video_url',
            field=models.URLField(help_text='A link to a recording of the record.', verbose_name='video URL'),
        ),
    ]
