# Generated by Django 2.1 on 2018-09-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0015_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-datetime']},
        ),
    ]
