# Generated by Django 2.1 on 2018-09-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0018_auto_20180902_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='information_url',
            field=models.URLField(blank=True, help_text='An optional information link for the event.', null=True, verbose_name='information URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='An optional video link for the event.', null=True, verbose_name='video URL'),
        ),
    ]
